filetypes = [{
        "extension": "3gp",
        "mime": "video/3gpp",
        "editable": false,
        "preview": true
    }, {
        "extension": "3g2",
        "mime": "video/3gpp2",
        "editable": false,
        "preview": true
    }, {
        "extension": "7z",
        "mime": "application/x-7z-compressed",
        "editable": false,
        "preview": false
    }, {
        "extension": "adp",
        "mime": "audio/adpcm",
        "editable": false,
        "preview": false
    }, {
        "extension": "aab",
        "mime": "application/x-authorware-bin",
        "editable": false,
        "preview": false
    }, {
        "extension": "aam",
        "mime": "application/x-authorware-map",
        "editable": false,
        "preview": false
    }, {
        "extension": "air",
        "mime": "application/vnd.adobe.air-application-installer-package+zip",
        "editable": false,
        "preview": false
    }, {
        "extension": "swf",
        "mime": "application/x-shockwave-flash",
        "editable": false,
        "preview": false
    }, {
        "extension": "pdf",
        "mime": "application/pdf",
        "editable": false,
        "preview": true
    }, {
        "extension": "xfdf",
        "mime": "application/vnd.adobe.xfdf",
        "editable": true,
        "preview": false
    }, {
        "extension": "aac",
        "mime": "audio/x-aac",
        "editable": false,
        "preview": true
    }, {
        "extension": "azw",
        "mime": "application/vnd.amazon.ebook",
        "editable": false,
        "preview": false
    }, {
        "extension": "apk",
        "mime": "application/vnd.android.package-archive",
        "editable": false,
        "preview": false
    }, {
        "extension": "dmg",
        "mime": "application/x-apple-diskimage",
        "editable": false,
        "preview": false
    }, {
        "extension": "mpkg",
        "mime": "application/vnd.apple.installer+xml",
        "editable": true,
        "preview": false
    }, {
        "extension": "s",
        "mime": "text/x-asm",
        "editable": true,
        "preview": false
    }, {
        "extension": "aif",
        "mime": "audio/x-aiff",
        "editable": false,
        "preview": true
    }, {
        "extension": "avi",
        "mime": "video/x-msvideo",
        "editable": false,
        "preview": false
    }, {
        "extension": "aep",
        "mime": "image/vnd.dxf",
        "editable": false,
        "preview": false
    }, {
        "extension": "dwf",
        "mime": "model/vnd.dwf",
        "editable": false,
        "preview": false
    }, {
        "extension": "par",
        "mime": "text/plain-bas",
        "editable": true,
        "preview": false
    }, {
        "extension": "bcpio",
        "mime": "application/x-bcpio",
        "editable": false,
        "preview": false
    }, {
        "extension": "bin",
        "mime": "application/octet-stream",
        "editable": false,
        "preview": false
    }, {
        "extension": "bmp",
        "mime": "image/bmp",
        "editable": false,
        "preview": true
    }, {
        "extension": "torrent",
        "mime": "application/x-bittorrent",
        "editable": false,
        "preview": false
    }, {
        "extension": "sh",
        "mime": "application/x-sh",
        "editable": true,
        "preview": false
    }, {
        "extension": "bz",
        "mime": "application/x-bzip",
        "editable": false,
        "preview": false
    }, {
        "extension": "bz2",
        "mime": "application/x-bzip",
        "editable": false,
        "preview": false
    }, {
        "extension": "csh",
        "mime": "application/x-csh",
        "editable": false,
        "preview": false
    }, {
        "extension": "c",
        "mime": "text/x-c",
        "editable": true,
        "preview": false
    }, {
        "extension": "css",
        "mime": "text/css",
        "editable": true,
        "preview": false
    }, {
        "extension": "cml",
        "mime": "chemical/x-cml",
        "editable": false,
        "preview": false
    }, {
        "extension": "ras",
        "mime": "image/x-cmu-raster",
        "editable": false,
        "preview": false
    }, {
        "extension": "csv",
        "mime": "text/csv",
        "editable": true,
        "preview": false
    }, {
        "extension": "cgm",
        "mime": "image/cgm",
        "editable": false,
        "preview": false
    }, {
        "extension": "deb",
        "mime": "application/x-debian-package",
        "editable": false,
        "preview": false
    }, {
        "extension": "dvi",
        "mime": "application/x-dvi",
        "editable": false,
        "preview": false
    }, {
        "extension": "dtb",
        "mime": "application/x-dtbook+xml",
        "editable": true,
        "preview": false
    }, {
        "extension": "res",
        "mime": "application/x-dtbresource+xml",
        "editable": true,
        "preview": false
    }, {
        "extension": "dtd",
        "mime": "application/xml-dtd",
        "editable": true,
        "preview": false
    }, {
        "extension": "dwg",
        "mime": "image/vnd.dwg",
        "editable": false,
        "preview": false
    }, {
        "extension": "exi",
        "mime": "application/exi",
        "editable": true,
        "preview": false
    }, {
        "extension": "epub",
        "mime": "application/epub+zip",
        "editable": false,
        "preview": false
    }, {
        "extension": "es",
        "mime": "application/ecmascript",
        "editable": true,
        "preview": false
    }, {
        "extension": "emma",
        "mime": "application/emma+xml",
        "editable": true,
        "preview": false
    }, {
        "extension": "flv",
        "mime": "video/x-flv",
        "editable": false,
        "preview": false
    }, {
        "extension": "g3",
        "mime": "image/g3fax",
        "editable": false,
        "preview": false
    }, {
        "extension": "bdf",
        "mime": "application/x-font-bdf",
        "editable": false,
        "preview": false
    }, {
        "extension": "kml",
        "mime": "application/vnd.google-earth.kml+xml",
        "editable": true,
        "preview": false
    }, {
        "extension": "hdf",
        "mime": "application/x-hdf",
        "editable": false,
        "preview": false
    }, {
        "extension": "hal",
        "mime": "application/vnd.hal+xml",
        "editable": true,
        "preview": false
    }, {
        "extension": "hta",
        "mime": "application/hta",
        "editable": true,
        "preview": false
    }, {
        "extension": "html",
        "mime": "text/html",
        "editable": true,
        "preview": false
    }, {
        "extension": "htm",
        "mime": "text/html",
        "editable": true,
        "preview": false
    }, {
        "extension": "ics",
        "mime": "text/calendar",
        "editable": true,
        "preview": false
    }, {
        "extension": "ico",
        "mime": "image/x-icon",
        "editable": false,
        "preview": true
    }, {
        "extension": "jar",
        "mime": "application/java-archive",
        "editable": false,
        "preview": false
    }, {
        "extension": "class",
        "mime": "application/java-vm",
        "editable": false,
        "preview": false
    }, {
        "extension": "ser",
        "mime": "application/java-serialized-object",
        "editable": false,
        "preview": false
    }, {
        "extension": "java",
        "mime": "text/x-java-source,java",
        "editable": true,
        "preview": false
    }, {
        "extension": "js",
        "mime": "application/javascript",
        "editable": true,
        "preview": false
    }, {
        "extension": "json",
        "mime": "application/json",
        "editable": true,
        "preview": false
    }, {
        "extension": "jpm",
        "mime": "video/jpm",
        "editable": false,
        "preview": false
    }, {
        "extension": "jpeg",
        "mime": "image/jpeg",
        "editable": false,
        "preview": true
    }, {
        "extension": "jpg",
        "mime": "image/jpeg",
        "editable": false,
        "preview": true
    }, {
        "extension": "pjpeg",
        "mime": "image/pjpeg",
        "editable": false,
        "preview": false
    }, {
        "extension": "jpgv",
        "mime": "video/jpeg",
        "editable": false,
        "preview": false
    }, {
        "extension": "m3u",
        "mime": "audio/x-mpegurl",
        "editable": false,
        "preview": false
    }, {
        "extension": "mobileconfig",
        "mime": "application/x-apple-aspen-config",
        "editable": true,
        "preview": false
    }, {
        "extension": "exe",
        "mime": "application/x-msdownload",
        "editable": false,
        "preview": false
    }, {
        "extension": "application",
        "mime": "application/x-ms-application",
        "editable": false,
        "preview": false
    }, {
        "extension": "xls",
        "mime": "application/vnd.ms-excel",
        "editable": false,
        "preview": false
    }, {
        "extension": "docx",
        "mime": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "editable": false,
        "preview": false
    }, {
        "extension": "pptx",
        "mime": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "editable": false,
        "preview": false
    }, {
        "extension": "ppt",
        "mime": "application/vnd.ms-powerpoint",
        "editable": false,
        "preview": false
    }, {
        "extension": "pub",
        "mime": "application/x-mspublisher",
        "editable": false,
        "preview": false
    }, {
        "extension": "doc",
        "mime": "application/msword",
        "editable": false,
        "preview": false
    }, {
        "extension": "wri",
        "mime": "application/x-mswrite",
        "editable": false,
        "preview": false
    }, {
        "extension": "mj2",
        "mime": "video/mj2",
        "editable": false,
        "preview": false
    }, {
        "extension": "mpga",
        "mime": "audio/mpeg",
        "editable": false,
        "preview": false
    }, {
        "extension": "mp4a",
        "mime": "audio/mp4",
        "editable": false,
        "preview": false
    }, {
        "extension": "mp4",
        "mime": "video/mp4",
        "editable": false,
        "preview": true
    }, {
        "extension": "mxml",
        "mime": "application/xv+xml",
        "editable": true,
        "preview": false
    }, {
        "extension": "n3",
        "mime": "text/n3",
        "editable": false,
        "preview": false
    }, {
        "extension": "oga",
        "mime": "audio/ogg",
        "editable": false,
        "preview": false
    }, {
        "extension": "ogv",
        "mime": "video/ogg",
        "editable": false,
        "preview": false
    }, {
        "extension": "png",
        "mime": "image/png",
        "editable": false,
        "preview": true
    }, {
        "extension": "ai",
        "mime": "application/postscript",
        "editable": false,
        "preview": false
    }, {
        "extension": "rtx",
        "mime": "text/richtext",
        "editable": true,
        "preview": false
    }, {
        "extension": "svg",
        "mime": "image/svg+xml",
        "editable": true,
        "preview": false
    }, {
        "extension": "txt",
        "mime": "text/plain",
        "editable": true,
        "preview": false
    }, {
        "extension": "ttf",
        "mime": "application/x-font-ttf",
        "editable": false,
        "preview": false
    }, {
        "extension": "unityweb",
        "mime": "application/vnd.unity",
        "editable": false,
        "preview": false
    }, {
        "extension": "vcs",
        "mime": "text/x-vcalendar",
        "editable": false,
        "preview": false
    }, {
        "extension": "wav",
        "mime": "audio/x-wav",
        "editable": false,
        "preview": true
    }, {
        "extension": "woff",
        "mime": "application/x-font-woff",
        "editable": false,
        "preview": false
    }, {
        "extension": "webp",
        "mime": "image/webp",
        "editable": false,
        "preview": false
    }, {
        "extension": "xhtml",
        "mime": "application/xhtml+xml",
        "editable": true,
        "preview": false
    }, {
        "extension": "xml",
        "mime": "application/xml",
        "editable": true,
        "preview": false
    }, {
        "extension": "zip",
        "mime": "application/zip",
        "editable": false,
        "preview": false
    }]
    toMime = function(filename) {
    var extension = filename.split(".").slice(-1)
    if (!filename.includes(".")) {
        extension = ""
    }
    return (filetypes.find(function(ext) {
        return ext.extension == extension
    }) || {
        extension: extension,
        mime: prompt(`Unknown filetype ".${extension}". Enter mime type`, "text/plain")
    })
}
